name: AnotherOxy's Blog CI/CD

on:
  push:
    branches: [main]
    paths:
      - '*.json'
      - '**.yml'
      - '**/source/**'

jobs:
  blog:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Initial Node
        run: |
          npm i
      - name: Install Hexo-Cli
        run: |
          npm i -g hexo-cli --save
      - name: 
        run: |
          hexo clean
          hexo g
      - name: Deploy Blog
        run: |
          git config --global user.name "sill-zhang"
          git config --global user.email "sill.zhang.c@hotmail.com"
          hexo d